export const SECONDS_BETWEEN_GUESSES = 60;

export const MILISECONDS_BETWEEN_GUESSES = SECONDS_BETWEEN_GUESSES * 1000;

export const SECONDS_BETWEEN_PRICE_UPDATES = 5;

export const MILISECONDS_BETWEEN_PRICE_UPDATES = SECONDS_BETWEEN_PRICE_UPDATES * 1000;
